services:
  app:
    container_name: app
    build: .
    ports:
      - 5001:5001
    volumes:
      - .:/app
    depends_on:
      - database
    links:
      - database

  database:
    container_name: database
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    env_file:
      - .env.development

volumes:
  database:
